# -*- coding: utf-8 -*-
"""SVM-Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11qWuyuwHYNKjZYXqqMP_o2Qcb06w1UBH
"""

from google.colab import drive
drive.mount('/content/gdrive')

from sklearn import svm
import numpy as np
import pandas as pd
import glob
import cv2
from PIL import Image
import tensorflow as tf

!unzip /content/gdrive/My\ Drive/test.zip

!unzip /content/gdrive/My\ Drive/train.zip

df = pd.read_csv('/content/gdrive/My Drive/labels_segmented/labels_segmented_train.csv')
df = df.iloc[6: , :]

dft = pd.read_csv('/content/gdrive/My Drive/labels_segmented/labels_segmented_test.csv')
dft = dft.iloc[8: , :]

numpy_arr = df.to_numpy()
print(numpy_arr[0][0])
cv_img_train = []
cv_img_train_labels = []
ctr = 0
for i in range(0, 200000):
    path = "/content/train/" + numpy_arr[i][0]
    #extension = numpy_arr[i][0]
    #print(path)
    img = glob.glob(path)
    if img:
        #print(i)
        colimg = Image.open(img[0])
        resized_image = colimg.resize((32,32))
        pix_val = list(resized_image.getdata())
        pix_val_flat = [x for sets in pix_val for x in sets]
        cv_img_train.append(pix_val_flat)
        cv_img_train_labels.append(numpy_arr[i][1])

numpy_arrt = dft.to_numpy()
print(numpy_arrt[0][0])
cv_img_test = []
cv_img_test_labels = []
ctr = 0
for i in range(0, 40000):
    path = "/content/test/" + numpy_arrt[i][0]
    #extension = numpy_arr[i][0]
    #print(path)
    img = glob.glob(path)
    if img:
        #print(i)
        colimg = Image.open(img[0])
        resized_image = colimg.resize((32,32))
        pix_val = list(resized_image.getdata())
        pix_val_flat = [x for sets in pix_val for x in sets]
        cv_img_test.append(pix_val_flat)
        cv_img_test_labels.append(numpy_arrt[i][1])

from sklearn import svm
svm_classifier = svm.SVC(gamma=0.001)
svm_classifier.fit(cv_img_train, cv_img_train_labels)
predicted = svm_classifier.predict(cv_img_test)

from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

print("\nAccuracy of the Algorithm: ", svm_classifier.score(cv_img_test, cv_img_test_labels))